export type ProductSummary = {
  name: string;
  href: string;
  status: string;
  tagline: string;
  description: string;
  bullets: string[];
  image: string;
  imageFit?: "cover" | "contain";
};

export type PrivacySection = {
  id: string;
  number: string;
  title: string;
  body?: string[];
  bullets?: string[];
};

export type TermsSection = {
  number: string;
  title: string;
  body: string[];
};

export const products: ProductSummary[] = [
  {
    name: "Bullion Master",
    href: "./bullion-master.html",
    status: "Live",
    tagline: "Daily Ledger, Net Daily Position, and secure backup for bullion operations.",
    description:
      "Bullion Master is the flagship JM Labs platform for precious metal businesses that need local-first records, faster daily operations, and tighter control over ledgers, stock, positions, reporting, and recovery workflows.",
    bullets: ["Daily Ledger, Master Ledger, and Net Daily Position", "Inventory, Refinery Desk, and Open Positions", "PIN security with local and cloud backup controls"],
    image:
      "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=1600&q=80",
  },
  {
    name: "Product in Development",
    href: "./next-product.html",
    status: "In Development",
    tagline: "The next JM Labs product is currently in active development.",
    description:
      "JM Labs is preparing a second focused software product. The parent site already includes it in the ecosystem so the next launch can sit alongside Bullion Master from day one.",
    bullets: ["Parent-brand ready", "Dedicated product page ready", "Connected legal and navigation structure"],
    image:
      "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1600&q=80",
  },
] ;

export const privacySections: PrivacySection[] = [
  {
    id: "overview",
    number: "01",
    title: "System Overview",
    body: [
      "Bullion Master is designed with a local-first approach. Most business records are stored on your device, and cloud features are used only for account, backup, restore, sync, and subscription workflows.",
      "This policy explains what information may be processed when you use the app, how it is used, and what control remains with you.",
    ],
  },
  {
    id: "storage",
    number: "02",
    title: "Data Stored Locally",
    bullets: [
      "Ledger and business records such as parties, items, transactions, expenses, income, stock, opening balances, and report context.",
      "Staff and payroll data including staff profile details and salary payment history.",
      "App settings and security preferences including units, categories, PIN protection settings, device-linked preferences, and backup configuration references.",
      "Attachments added by you, such as bill or record images, through app attachment workflows.",
      "Operational state generated by the app, such as archive reports, startup progress metadata, opening stock context, and other internal records required for feature continuity.",
    ],
  },
  {
    id: "auth",
    number: "03",
    title: "Account & Authentication",
    body: [
      "To use authenticated features, account data such as email and authentication identifiers are processed via authentication services. This supports sign in, verification, profile access, device registration, subscription entitlement checks, and account recovery flows.",
      "Depending on the feature, limited device or installation identifiers may also be processed to help with account security, device management, session integrity, or feature enforcement.",
    ],
  },
  {
    id: "backup",
    number: "04",
    title: "Cloud Backup Architecture",
    body: [
      "If you enable cloud backup or sync features, your backup package and backup metadata such as backup identifier or timestamp are used to support restore and multi-device continuity.",
    ],
    bullets: [
      "Backups may be handled in encrypted format based on your configured backup or password workflow.",
      "Access to backup contents depends on valid credentials or password where encryption is enabled.",
      "Cloud features require active network connectivity and supported account state.",
      "Backup content can include the business records and configuration data you choose to store in the app, subject to the backup flow you use.",
    ],
  },
  {
    id: "security",
    number: "05",
    title: "Security Events",
    body: [
      "The app may process local security events to protect data access, such as PIN checks, failed-attempt counters, auto-wipe configuration, and emergency or duress-triggered protection flows.",
      "These protections are intended to reduce unauthorized access risk, but no device, software, storage, or transmission method can be guaranteed fully secure in every case.",
    ],
    bullets: [
      "PIN checks and session integrity flows.",
      "Failed-attempt counters and auto-wipe configuration.",
      "Emergency or duress-triggered protection flows.",
    ],
  },
  {
    id: "usage",
    number: "06",
    title: "How We Use Information",
    bullets: [
      "To operate core ledger, inventory, reporting, archive, and workflow features.",
      "To authenticate users and maintain account access.",
      "To provide backup, restore, sync, export, and sharing flows requested by you.",
      "To protect access through security checks, PIN workflows, and device-related safeguards.",
      "To validate subscription, trial, and feature entitlement state.",
    ],
  },
  {
    id: "permissions",
    number: "07",
    title: "Permissions We Use",
    bullets: [
      "Internet and network access for login, authentication, cloud backup and restore, and subscription checks.",
      "Camera and photo access only when you capture or select images for record attachments.",
      "Filesystem, cache, and share access for exports, local backup files, open-file actions, and user-initiated sharing.",
    ],
  },
  {
    id: "sharing",
    number: "08",
    title: "Data Sharing and Disclosure",
    body: [
      "We do not sell your business data. Data may be shared only as required for service operation, such as authentication or cloud infrastructure, or when you explicitly trigger actions like export, share, or restore.",
      "Information may also be disclosed where required by applicable law, lawful process, or to protect rights, security, fraud prevention, or service integrity.",
    ],
  },
  {
    id: "retention",
    number: "09",
    title: "Retention and Deletion",
    bullets: [
      "Local app data stays on your device until you edit, delete, wipe, or reset app data.",
      "Restore operations can overwrite current local records with backup contents.",
      "Security wipe flows may permanently remove local records.",
      "Cloud backup retention may depend on the storage service, account state, overwrite actions, or deletion actions initiated by you.",
    ],
  },
  {
    id: "controls",
    number: "10",
    title: "Your Controls and Responsibilities",
    body: [
      "You can manage your information using built-in tools such as edit screens, export, backup, restore, and account or security settings. Because backup security depends on your credentials, keep your PIN and backup password confidential.",
      "You are responsible for verifying what information you enter, choosing whether to use cloud or attachment features, maintaining secure access to your device and account, and testing your own backup and recovery process.",
    ],
  },
  {
    id: "updates",
    number: "11",
    title: "Policy Updates",
    body: [
      "We may update this Privacy Policy to reflect feature, legal, or operational changes. The latest version and date shown in the app are the governing version.",
    ],
  },
] ;

export const termsSections: TermsSection[] = [
  {
    number: "01",
    title: "Acceptance and Eligibility",
    body: [
      "By downloading, installing, accessing, activating a subscription or trial, or otherwise using Bullion Master, you acknowledge that you have read, understood, and agreed to be legally bound by these terms.",
      "If you do not agree, you must not use the app. You must use the app only for lawful business operations and be authorized to manage the data entered in your account.",
    ],
  },
  {
    number: "02",
    title: "Intended Use and User Responsibility",
    body: [
      "Bullion Master is a workflow-assistance tool intended to help you record, organize, review, and operate ledger, stock, reporting, archive, and related business processes more efficiently.",
      "It is not a substitute for your own review, supervision, reconciliation, internal controls, accounting judgment, tax advice, legal advice, or business decision-making.",
    ],
  },
  {
    number: "03",
    title: "Data Ownership and Account Control",
    body: [
      "You retain ownership of business data entered in the app. You are responsible for account credentials, PIN, backup password, and any recovery details such as backup email.",
    ],
  },
  {
    number: "04",
    title: "Security Features and Irreversible Actions",
    body: [
      "The app may provide security features such as PIN lock, auto-wipe controls, and emergency or duress-triggered wipe flows.",
      "Wipe actions can permanently remove local data and may be irreversible. You must keep secure copies of backup credentials and test your recovery process periodically.",
    ],
  },
  {
    number: "05",
    title: "Cloud Features",
    body: [
      "Cloud backup, sync, restore, subscription checks, and authentication require internet or network availability and third-party platform services. Availability or response time may vary.",
    ],
  },
  {
    number: "06",
    title: "Permissions Used by Features",
    body: [
      "Internet and network access is used for authentication, cloud backup and restore, and subscription validation.",
      "Camera and photo access is used only when you add image attachments to records. Files, storage, and share access is used for export, backup files, file open, and user-initiated sharing.",
    ],
  },
  {
    number: "07",
    title: "Employee and Third-Party Data",
    body: [
      "If you store staff, customer, or supplier details such as mobile number, ID details, or salary records, you must ensure lawful collection, use, and retention under applicable laws and internal policy.",
    ],
  },
  {
    number: "08",
    title: "Output Verification and No Professional Advice",
    body: [
      "Information, calculations, previews, summaries, analytics, archive results, settlement outputs, stock views, profit and loss figures, balances, reports, exports, and other app-generated results are provided only as operational assistance.",
      "They may depend on user input, device state, configuration, third-party services, backup state, connectivity, timing, or software limitations. They must be independently checked by you before use.",
    ],
  },
  {
    number: "09",
    title: "Refund Policy",
    body: [
      "All payments, subscription charges, upgrade fees, and other amounts paid for Bullion Master are final and non-refundable to the maximum extent permitted by applicable law.",
      "We do not provide refunds, credits, partial refunds, pro-rated refunds, or exchanges for reasons including unused time, reduced usage, mistaken purchase, device change, account change, business closure, feature preference, dissatisfaction, or service discontinuation by you.",
    ],
  },
  {
    number: "10",
    title: "Limitation of Liability",
    body: [
      "To the extent permitted by law, the app is provided on an as-is and as-available basis. We do not guarantee uninterrupted operation, error-free computation, or suitability for every workflow.",
      "To the maximum extent permitted by law, we will not be liable for loss or damage arising from use of the app, including data loss, reporting mistakes, reconciliation differences, missed settlements, backup failure, restore failure, security incidents, or actions taken based on app output.",
    ],
  },
  {
    number: "11",
    title: "Indemnity",
    body: [
      "You agree to be responsible for claims, losses, or liabilities arising from unlawful use of the app, unauthorized data usage, or violation of these terms by your account activity.",
    ],
  },
  {
    number: "12",
    title: "Updates to Terms",
    body: [
      "We may revise these terms from time to time. The version shown in the app will govern from its stated effective date. Your continued use of Bullion Master after any update constitutes acceptance of the revised terms.",
    ],
  },
] ;
